version: '3'
services:
  caddy:
    # Shadow use of rothgar caddy docker image : upgrade to Caddy V2 for security
    # image: rothgar/rpi-caddy:0.9.1
    build: caddy

    volumes:
      - "./.data/wp:/srv"
      # Path to folder containing fullchain.pem and privkey.pem if you'd like to provide HTTPS/SSL service
      - "${PATH_TO_CERTS_LIVE}/${DOMAIN_NAME}:/cert/live/${DOMAIN_NAME}:ro" 
      - "${PATH_TO_CERTS_ARCHIVE}/${DOMAIN_NAME}:/cert/archive/${DOMAIN_NAME}:ro"

    depends_on:
      - mysql
      - php

    ports:
      - "80:80"
      - "443:443"

    env_file:
      - ./.env 

    restart: always

  php:
    image: rothgar/rpi-php:5.6
    #build: php
    links:
      # make sure you change your wp-config
      - mysql:mysql

    volumes:
      - "./.data/wp:/srv"

    restart: always

  mysql:
    image: rothgar/rpi-mysql:5.5
    #build: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.data/backup/1n7:/docker-entrypoint-initdb.d"

    env_file:
      - ./.env

    restart: always 


# Use these images for dynamic DDNS updates
# For Google domains use http://j.mp/2bRNYET
# Make sure you update WWW and @ DNS entries
#
#  inadyn:
#    image: rothgar/rpi-inadyn:1.99.15
#    environment:
#      SYSTEM: default@domains.google.com
#      USERNAME: UUUUU
#      PASSWORD: PPPPP
#      ALIAS: example.com
#
#  inadyn_www:
#    image: rothgar/rpi-inadyn:1.99.15
#    environment:
#      SYSTEM: default@domains.google.com
#      USERNAME: UUUUU
#      PASSWORD: PPPPP
#      ALIAS: www.example.com
